name: anoopastro_light
description: A light kundali astrology app with offline features
publish_to: "none" # Private app
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # Fonts
  google_fonts: ^6.2.1  # Compatible with Dart 3.4.0

  # PDF generation & printing
  pdf: ^3.11.3
  printing: ^5.9.0

  # File paths
  path_provider: ^2.1.5

  # Vector graphics
  flutter_svg: ^2.1.0

  # Internationalization
  intl: ^0.20.2

  # Sweph for astrology calculations
  sweph: ^2.10.3+18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/cities/cities.json
    - assets/ephem/ephem_1950_2050.dat
