name: anoopastro_light
description: A light kundali app with AnoopAstro branding.
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # date/time formatting
  intl: ^0.18.0

  # location (nearest-city autofill)
  geolocator: ^9.0.2

  # PDF generation & printing (export horoscope)
  pdf: ^3.10.1
  printing: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cities.json
