name: anoopastro_light
description: A light kundali app with AnoopAstro branding.
publish_to: "none" # private app

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI + Fonts
  google_fonts: ^6.2.1

  # Date formatting
  intl: ^0.19.0

  # PDF generation
  pdf: ^3.11.0
  printing: ^5.13.0

  # For Material 3 widgets
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
