name: anoopastro_light
description: A fully offline astrology app with AnoopAstro branding.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^10.0.0
  path_provider: ^2.4.2
  pdf: ^3.12.2
  printing: ^5.12.0
  sweph: ^3.2.1+2.10.3
  intl: ^0.20.2
  provider: ^6.1.6
  flutter_svg: ^2.2.1
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cities/cities.json
    - assets/ephem/ephem_1950_2050.dat
