name: anoopastro_light
description: A light kundali app with AnoopAstro branding.
publish_to: "none" # private app
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  async: ^2.11.0
  characters: ^1.3.0
  collection: ^1.18.0
  ffi: ^2.1.3
  http_parser: ^4.0.2
  intl: ^0.19.0
  meta: ^1.12.0
  path: ^1.9.0
  typed_data: ^1.3.2
  vector_math: ^2.1.4
  xml: ^6.5.0

  # UI packages
  google_fonts: 6.3.0
  flutter_svg: ^2.1.0
  share_plus: 10.1.4

  # Offline astronomy calculation
  sweph: 2.10.3+18

  # Storage & file handling
  path_provider: 2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_async: 1.3.1
  matcher: 0.12.16+1

flutter:
  uses-material-design: true

  assets:
    - assets/cities/cities.json
    - assets/ephem/ephem_1950_2050_3h.bin.gz
