name: anoopastro_light
description: A fully offline astrology app with AnoopAstro branding.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^9.0.2           # compatible with Flutter 3.22
  path_provider: ^2.1.5        # compatible with Flutter 3.22
  pdf: ^3.12.2
  printing: ^5.9.0             # slightly older version for compatibility
  sweph: ^2.10.3+18
  intl: ^0.19.0
  provider: ^6.0.5             # compatible with Flutter 3.22
  flutter_svg: ^2.1.0
  google_fonts: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cities/cities.json
    - assets/ephem/ephem_1950_2050.dat
