name: anoopastro_light
description: A full-featured Kundali app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sweph: ^2.10.3+18
  pdf: ^3.11.0
  printing: ^5.12.4
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  intl: ^0.20.2
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/cities/cities.json
    - assets/ephem/ephem_1950_2050_3h.bin.gz
