name: anoopastro_light
description: A full-featured Kundali app with planetary positions, houses, and Dasha
publish_to: "none" # private app

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Swiss Ephemeris Dart binding for accurate planetary positions
  sweph: ^0.0.6

  # For PDF generation and sharing
  pdf: ^3.11.0
  printing: ^5.12.4
  share_plus: ^10.0.2

  # Utilities
  path_provider: ^2.1.5
  intl: ^0.20.2
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/cities/cities.json
    # You can include ephemeris files if you still want your own bin.gz files
    # - assets/ephem/ephem_1950_2050_3h.bin.gz
