name: astro_app_full
description: A standalone offline astrology app with kundali and dasha.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_typeahead: ^5.2.0
  pdf: ^3.10.7
  path_provider: ^2.1.2
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/cities.json
