import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfGenerator {
  static Future<pw.Document> generateKundaliPdf({
    required Map<String,double> planets,
    required String city,
    required DateTime birthDate,
  }) async {
    final pdf = pw.Document();
    pdf.addPage(
      pw.Page(
        build: (pw.Context ctx) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text("Anoopastro Light", style: pw.TextStyle(fontSize: 20)),
              pw.SizedBox(height: 10),
              pw.Text("Birth: $city"),
              pw.Text("Date: $birthDate"),
              pw.SizedBox(height: 20),
              pw.Text("Planets:"),
              for (var e in planets.entries)
                pw.Text("${e.key}: ${e.value.toStringAsFixed(2)}°"),
              pw.Spacer(),
              pw.Text("Generated by Anoopastro", style: pw.TextStyle(fontSize: 12)),
            ],
          );
        },
      ),
    );
    return pdf;
  }

  static Future<void> saveAndShare(pw.Document pdf) async {
    final dir = await getTemporaryDirectory();
    final file = File("${dir.path}/kundali.pdf");
    await file.writeAsBytes(await pdf.save());
    await Printing.sharePdf(bytes: await pdf.save(), filename: 'kundali.pdf');
  }
}