import 'dart:io';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfGenerator {
  static Future<pw.Document> generateKundaliPdf({
    required Map<String, double> planets,
    required List<double> houses,
    required String city,
    required DateTime birthDate,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context ctx) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text("AnoopAstro Light", style: pw.TextStyle(fontSize: 20)),
              pw.SizedBox(height: 10),
              pw.Text("Birth Place: $city"),
              pw.Text("Date: ${birthDate.toLocal()}"),
              pw.SizedBox(height: 20),
              pw.Text("Planets:"),
              ...planets.entries.map((e) => pw.Text("${e.key}: ${e.value.toStringAsFixed(2)}°")),
              pw.SizedBox(height: 20),
              pw.Text("Houses:"),
              ...houses.map((h) => pw.Text(h.toStringAsFixed(2))),
              pw.Spacer(),
              pw.Text("Generated by Anoopastro Light", style: pw.TextStyle(fontSize: 12)),
            ],
          );
        },
      ),
    );

    return pdf;
  }

  static Future<void> saveAndShare(pw.Document pdf) async {
    final bytes = await pdf.save();
    await Printing.sharePdf(bytes: bytes, filename: 'kundali.pdf');
  }
}
