name: Unzip Astro App

on:
  workflow_dispatch:   # Run manually

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unzip astro_app(1).zip
        run: |
          unzip "astro_app(1).zip" -d .
          rm "astro_app(1).zip"
      - name: Commit unzipped files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzipped astro_app"
          git push
