name: Unzip Android Folder

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unzip android folder
        run: |
          unzip android_visible_folder.zip -d .
      - name: Commit extracted android folder
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add android
          git commit -m "Added android folder"
          git push
